# Generated by Django 3.0.6 on 2020-05-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='small',
            field=models.FloatField(),
        ),
    ]
