# Generated by Django 3.0.6 on 2020-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='large',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small',
            field=models.FloatField(blank=True),
        ),
    ]
