# Generated by Django 3.0.6 on 2020-05-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200511_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=20)),
                ('small', models.FloatField()),
                ('large', models.FloatField()),
            ],
        ),
    ]
