# Generated by Django 3.0.6 on 2020-05-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_dinnerplate_pasta_salad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='base',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('SICILIAN', 'SICILIAN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('CHEESE', 'CHEESE'), ('ONE', 'ONE TOPPING'), ('TWO', 'TWO TOPPINGS'), ('THREE', 'THREE TOPPINGS'), ('SPECIAL', 'SPECIAL')], max_length=20),
        ),
    ]
