# Generated by Django 3.0.6 on 2020-05-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200511_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='large',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='small',
        ),
    ]
