# Generated by Django 3.0.6 on 2020-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200511_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='new',
            field=models.IntegerField(default=0),
        ),
    ]
