# Generated by Django 3.0.6 on 2020-05-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_pizza_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='new',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
