# Generated by Django 3.0.6 on 2020-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200511_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('CHEESE', 'CHEESE'), ('ONE', 'ONE TOPPING')], default='SMALL', max_length=20),
            preserve_default=False,
        ),
    ]
