# Generated by Django 3.0.6 on 2020-05-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200511_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='base',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('SICILIAN', 'SICILIAN')], max_length=20),
        ),
    ]
