# Generated by Django 3.0.6 on 2020-05-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200511_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaBaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='dinnerplate',
            name='large',
        ),
        migrations.RemoveField(
            model_name='dinnerplate',
            name='small',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='large',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='small',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='large',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='small',
        ),
        migrations.AddField(
            model_name='dinnerplate',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AddField(
            model_name='extra',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaBaseType'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaTopping'),
        ),
    ]
