# Generated by Django 3.0.6 on 2020-05-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200512_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplate',
            name='size',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaBaseType'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaTopping'),
        ),
    ]
