# Generated by Django 3.0.6 on 2020-05-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200512_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplate',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dinnerplate',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AddField(
            model_name='extra',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sub',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
