# Generated by Django 3.0.6 on 2020-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200518_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='price',
            new_name='large',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='small',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='PizzaPriceTable',
        ),
    ]
