# Generated by Django 3.0.6 on 2020-05-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20200518_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='relatedItem',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
