# Generated by Django 3.0.6 on 2020-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='toppings',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
