# Generated by Django 3.0.6 on 2020-05-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_orderitem_toppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='toppings',
            new_name='extras',
        ),
    ]
