# Generated by Django 3.0.6 on 2020-05-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20200520_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
