# Generated by Django 3.0.6 on 2020-05-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20200520_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='relatedItem',
        ),
    ]
